# Generated by Django 5.2.6 on 2025-09-24 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='الرقم')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('raw_content', models.TextField(verbose_name='المحتوى الخام لرمز QR')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رمز QR',
                'verbose_name_plural': 'رموز QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
